import Modal from "@/components/Modal";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Tazheeb Shamsi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
